version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0

    volumes:
      - .:/app
    expose:
      - 8000
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/postgres
      - JWT_SECRET_KEY=
      - JWT_ALGORITHM=HS256
    depends_on:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)'

  db:
    image: postgres:15-alpine
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  traefik:
    image: traefik:v2.9.6
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - './traefik.dev.toml:/etc/traefik/traefik.toml'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

volumes:
  postgres_data:
